# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Ali Sabzevari'
tagline:          'Ali Sabzevari's Personal Blog'
description:      'Ali Sabzevari's personal blog about technology and the other things!'
url:              http://alisabzevari.github.io
baseurl:          /

author:
  name:           'Ali Sabzevari'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
